[build]
  command = "pnpm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/open-food-facts/:barcode"
  to = "/.netlify/functions/open-food-facts?barcode=:barcode"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
