import { expect, test, type Page } from '@playwright/test'

const key = 'cutting-performance-app:v1'
test.beforeEach(async ({ page }) => { await page.goto('/seances'); await page.evaluate(() => localStorage.clear()); await page.reload() })
const read = (page: Page) => page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key)
async function addExercise(page: Page, name = 'Pec deck') {
  await page.getByRole('button', { name: 'Ajouter un exercice', exact: true }).click()
  await page.getByLabel('Chercher un exercice').fill(name)
  await page.locator('.exercise-catalogue').getByText(name, { exact: true }).click()
  await page.getByRole('button', { name: 'Confirmer le choix' }).click()
}
async function start(page: Page) { await page.goto('/seances/journal'); await page.getByRole('button', { name: 'Démarrer la séance' }).click() }

test('créer cinq exercices, réordonner, sauvegarder, dupliquer et rechercher', async ({ page }) => {
  await page.getByRole('link', { name: 'Créer une séance', exact: true }).click()
  await page.getByLabel('Nom de la séance').fill('Lower personnalisé TEST')
  await page.getByLabel('Type de journée').selectOption('lower')
  for (const name of ['Pec deck', 'Hack squat', 'Leg extension', 'Mollets debout', 'Curl poulie']) await addExercise(page, name)
  await page.getByRole('button', { name: 'Monter Curl poulie' }).click()
  await page.getByRole('button', { name: 'Enregistrer le modèle', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Lower personnalisé TEST')
  await page.reload()
  expect((await read(page)).templates.find((t: any) => t.name === 'Lower personnalisé TEST').exercises[3].name).toBe('Curl poulie')
  await page.goto('/seances')
  await page.getByLabel('Rechercher une séance').fill('LOWER personnalise test')
  await expect(page.locator('.template-card')).toHaveCount(1)
  await page.getByRole('button', { name: 'Dupliquer Lower personnalisé TEST' }).click()
  await expect(page.locator('.template-card')).toHaveCount(2)
  const templates = (await read(page)).templates.filter((t: any) => t.name.startsWith('Lower personnalisé TEST'))
  expect(templates[0].id).not.toBe(templates[1].id)
  expect(templates[0].exercises[0].id).not.toBe(templates[1].exercises[0].id)
})

test('un brouillon prévient avant navigation et un formulaire vide ne sauvegarde pas', async ({ page }) => {
  await page.goto('/seances/nouvelle')
  await page.getByRole('button', { name: 'Enregistrer le modèle', exact: true }).click()
  await expect(page.getByLabel('Nom de la séance')).toBeFocused()
  await page.getByLabel('Nom de la séance').fill('Brouillon TEST')
  await page.locator('.session-tabs').getByRole('link', { name: 'Planning', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Quitter le brouillon')
  await page.getByRole('button', { name: 'Continuer la modification' }).click()
  await expect(page.getByLabel('Nom de la séance')).toHaveValue('Brouillon TEST')
})

test('aperçu planning, annulation, confirmation et conservation des saisies', async ({ page }) => {
  const date = await page.getByLabel('Choisir la date du journal').inputValue()
  await page.goto('/nutrition')
  await page.getByLabel('Calories consommées aujourd’hui').fill('2800')
  await page.getByRole('button', { name: /Enregistrer 2.?800 kcal/ }).click()
  await page.goto('/seances/planning')
  const before = await read(page)
  const day = page.locator('.planning-day').filter({ has: page.locator(`select[aria-label="Séance du ${date}"]`) })
  await day.getByRole('button', { name: 'Épaules-bras', exact: true }).click()
  await page.getByRole('dialog').getByRole('radio', { name: /Lower A/ }).check()
  await page.getByRole('button', { name: 'Appliquer à ce jour (aperçu)' }).click()
  expect((await read(page)).schedule[date]).toBe(before.schedule[date])
  await expect(page.locator('.planning-preview')).toContainText('Cible finale')
  await page.getByRole('button', { name: 'Annuler les changements' }).click()
  expect((await read(page)).logs[date]).toEqual(before.logs[date])
  await day.getByRole('button', { name: 'Épaules-bras', exact: true }).click()
  await page.getByRole('dialog').getByRole('radio', { name: /Lower A/ }).check()
  await page.getByRole('button', { name: 'Appliquer à ce jour (aperçu)' }).click()
  await page.getByRole('button', { name: 'Enregistrer le planning' }).click()
  await page.getByRole('button', { name: 'Confirmer le planning' }).click()
  await expect(page.getByText('Planning enregistré. Toutes les cibles ont été recalculées.')).toBeVisible()
  await page.reload()
  const after = await read(page)
  expect(after.logs[date].caloriesConsumed).toBe(2800)
  expect(after.logs[date].plannedBaseCalories).toBe(after.settings.dayTypePlans.lower.calories)
  await page.goto('/aujourdhui')
  await expect(page.locator('.daily-summary-card')).toContainText('Lower A')
})

test('séries, reprise, cinquième série, remplacement local et statistique datée', async ({ page, isMobile }) => {
  await start(page)
  const first = page.locator('.journal-exercise').first()
  const name = 'Élévations latérales machine'
  await page.getByLabel(`Charge série 1 ${name}`, { exact: true }).fill('30')
  await page.getByLabel(`Répétitions série 1 ${name}`, { exact: true }).fill('12')
  await page.getByRole('button', { name: `Valider série 1 ${name}`, exact: true }).click()
  await page.reload()
  await expect(page.getByLabel(`Charge série 1 ${name}`, { exact: true })).toHaveValue('30')
  await first.getByRole('button', { name: 'Ajouter une série', exact: true }).filter({ visible: true }).click()
  await expect(first.locator('.set-row')).toHaveCount(6)
  await first.getByRole('button', { name: isMobile ? 'Remplacer l’exercice' : `Remplacer ${name}`, exact: true }).click()
  await page.getByLabel('Chercher un exercice').fill('Pec deck')
  await page.locator('.exercise-catalogue').getByText('Pec deck', { exact: true }).click()
  await page.getByRole('button', { name: 'Confirmer le choix' }).click()
  const saved = await read(page)
  const date = await page.getByLabel('Choisir la date du journal').inputValue()
  const actual = saved.logs[date].training.exercises
  expect(actual[0].name).toBe(name)
  expect(actual[0].sets).toHaveLength(1)
  expect(actual[1].name).toBe('Pec deck')
  expect(saved.templates.find((t: any) => t.id === 'shoulders-arms').exercises[0].name).toBe(name)
  await page.getByRole('button', { name: 'Terminer la séance', exact: true }).click()
  await page.getByRole('button', { name: 'Terminer en l’état' }).click()
  await page.goto('/seances/statistiques?exerciseId=lateral-machine&equipmentId=legacy-unspecified')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.getByRole('link', { name: `Voir la séance du ${date}` }).click()
  await expect(page).toHaveURL(/lineId=/)
  await expect(page.locator('.highlight-exercise')).toContainText(name)
  await page.goBack()
  await expect(page.getByLabel('Exercice', { exact: true })).toHaveValue('lateral-machine')
})

test('dates futures protégées et archives non destructrices', async ({ page }) => {
  const date = await page.getByLabel('Choisir la date du journal').inputValue()
  const future = new Date(`${date}T12:00:00`); future.setDate(future.getDate() + 7)
  const futureDate = future.toISOString().slice(0, 10)
  await page.goto(`/seances/journal?date=${futureDate}`)
  await expect(page.getByRole('heading', { name: 'Journal futur en lecture seule' })).toBeVisible()
  await page.goto('/seances')
  const before = await read(page)
  await page.getByRole('button', { name: 'Archiver Lower A', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmer l’archivage' }).click()
  const after = await read(page)
  expect(after.templates.find((t: any) => t.id === 'lower-a').archived).toBe(true)
  expect(after.schedule).toEqual(before.schedule)
  expect(after.logs).toEqual(before.logs)
  await page.getByLabel('Archives', { exact: true }).check()
  await expect(page.locator('.template-card')).toHaveCount(1)
})

test('JSON corrompu récupérable et erreur de quota sans message de succès', async ({ page }) => {
  await page.evaluate(key => localStorage.setItem(key, '{broken'), key)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Ton journal est protégé' })).toBeVisible()
  expect(await page.evaluate(key => localStorage.getItem(key), key)).toBe('{broken')
  await page.evaluate(() => localStorage.clear()); await page.reload()
  await page.goto('/seances/nouvelle')
  await page.getByLabel('Nom de la séance').fill('Quota TEST')
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Quota', 'QuotaExceededError') } })
  await page.getByRole('button', { name: 'Enregistrer le modèle', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Échec de sauvegarde')
  await expect(page).toHaveURL(/nouvelle/)
  await expect(page.getByLabel('Nom de la séance')).toHaveValue('Quota TEST')
})

test('dialogue accessible au clavier et aucun débordement global', async ({ page }) => {
  await page.goto('/seances/nouvelle')
  const add = page.getByRole('button', { name: 'Ajouter un exercice', exact: true })
  await add.click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Tab')
  expect(await page.evaluate(() => !!document.activeElement?.closest('dialog'))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(add).toBeFocused()
  for (const width of [360, 390, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    for (const route of ['/seances', '/seances/planning', '/seances/statistiques', '/seances/journal']) {
      await page.goto(route)
      await expect(page.locator('h1')).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), `${route} at ${width}`).toBe(true)
    }
  }
})

test('catalogue personnalisé : brouillon conservé à la fermeture et matériel explicite', async ({ page }) => {
  await page.goto('/seances/nouvelle')
  await page.getByLabel('Nom de la séance').fill('Séance équipement TEST')
  await page.getByRole('button', { name: 'Ajouter un exercice', exact: true }).click()
  await page.getByRole('button', { name: 'Créer un exercice personnalisé', exact: true }).click()
  await page.getByLabel('Nom de l’exercice', { exact: true }).fill('Rowing personnalisé TEST')
  await page.getByLabel('Matériel / variante', { exact: true }).fill('Machine salle A')
  await page.getByLabel('Convention de charge', { exact: true }).selectOption('machine')
  await page.getByRole('button', { name: 'Fermer le panneau' }).click()
  await page.getByRole('button', { name: 'Ajouter un exercice', exact: true }).click()
  await expect(page.getByLabel('Nom de l’exercice', { exact: true })).toHaveValue('Rowing personnalisé TEST')
  await page.getByRole('button', { name: 'Créer dans le catalogue', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmer le choix' }).click()
  await page.getByRole('button', { name: 'Enregistrer le modèle', exact: true }).click()
  await page.reload()
  await expect(page.locator('.prescription-title')).toContainText('Machine salle A')
  expect((await read(page)).catalogue.find((d: any) => d.name === 'Rowing personnalisé TEST').convention).toBe('machine')
})

test('répétition de semaine et échange de journées sans copier de performances', async ({ page, isMobile }) => {
  await page.goto('/seances/planning')
  const before = await read(page)
  await page.getByRole('button', { name: 'Répéter la semaine', exact: true }).click()
  const target = await page.getByLabel('Semaine destination', { exact: true }).inputValue()
  await page.getByRole('button', { name: 'Prévisualiser la copie', exact: true }).click()
  expect((await read(page)).schedule).toEqual(before.schedule)
  await expect(page.locator('.planning-preview')).toContainText('Cible finale')
  await page.getByRole('button', { name: 'Enregistrer le planning', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmer le planning', exact: true }).click()
  const after = await read(page)
  expect(Object.values(after.logs).filter((l: any) => l.training)).toHaveLength(0)
  expect(after.logs[target].caloriesConsumed).toBeUndefined()
  if (!isMobile) {
    await page.goto(`/seances/planning?week=${target}`)
    const cards = page.locator('.planning-day')
    await cards.nth(0).locator('button.day-pill').dragTo(cards.nth(1))
    await expect(page.getByRole('dialog')).toContainText('Déplacer cette séance')
    await page.getByRole('button', { name: 'Échanger les deux jours' }).click()
    await expect(page.locator('.planning-preview>div')).toHaveCount(2)
    await page.getByRole('button', { name: 'Annuler les changements' }).click()
    expect((await read(page)).schedule).toEqual(after.schedule)
  }
})

test('deux onglets : les changements récents ne sont pas écrasés', async ({ page, context }) => {
  await page.goto('/seances/upper-a/modifier')
  await page.getByLabel('Nom de la séance', { exact: true }).fill('Premier brouillon TEST')
  const second = await context.newPage()
  await second.goto('/seances/upper-a/modifier')
  await second.getByLabel('Nom de la séance', { exact: true }).fill('Version récente TEST')
  await second.getByRole('button', { name: 'Enregistrer le modèle', exact: true }).click()
  await expect(second.locator('h1')).toHaveText('Version récente TEST')
  await page.bringToFront()
  await page.getByRole('button', { name: 'Enregistrer le modèle', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('autre onglet')
  expect((await read(page)).templates.find((t: any) => t.id === 'upper-a').name).toBe('Version récente TEST')
  await second.close()
})

test('minuteur, pause et suppression annulable conservent leurs états', async ({ page }) => {
  await start(page)
  const name = 'Élévations latérales machine'
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const date = await page.getByLabel('Choisir la date du journal').inputValue()
  const paused = (await read(page)).logs[date].training.elapsedMs
  await page.reload()
  expect((await read(page)).logs[date].training.elapsedMs).toBe(paused)
  await page.getByRole('button', { name: 'Reprendre', exact: true }).click()
  await page.getByRole('button', { name: 'Démarrer le repos', exact: true }).click()
  const rest = (await read(page)).logs[date].training.restUntil
  await page.getByRole('button', { name: '+30 s', exact: true }).click()
  expect((await read(page)).logs[date].training.restUntil).toBe(rest + 30000)
  await page.getByLabel(`Charge série 1 ${name}`, { exact: true }).fill('20')
  await page.getByLabel(`Répétitions série 1 ${name}`, { exact: true }).fill('15')
  await page.getByRole('button', { name: `Valider série 1 ${name}`, exact: true }).click()
  await page.getByRole('button', { name: `Retirer série 1 ${name}`, exact: true }).click()
  await page.getByRole('button', { name: 'Confirmer la suppression', exact: true }).click()
  await page.getByRole('button', { name: 'Annuler la suppression', exact: true }).click()
  await expect(page.getByLabel(`Charge série 1 ${name}`, { exact: true })).toHaveValue('20')
  expect((await read(page)).logs[date].training.exercises[0].sets[0].completed).toBe(true)
})

test('édition globale confirmée : la séance active reste indépendante', async ({ page }) => {
  await start(page)
  const date = await page.getByLabel('Choisir la date du journal').inputValue()
  const original = (await read(page)).logs[date].training
  await page.goto('/seances/shoulders-arms/modifier')
  await page.getByLabel('Nom de la séance', { exact: true }).fill('Modèle modifié TEST')
  await page.getByRole('radio', { name: /Inclure les séances planifiées non démarrées/ }).check()
  await page.getByRole('button', { name: 'Enregistrer le modèle', exact: true }).click()
  await expect(page.getByRole('dialog').locator('.planning-impact')).toContainText('Cible :')
  await page.getByRole('button', { name: 'Confirmer et enregistrer', exact: true }).click()
  await expect(page.locator('h1')).toHaveText('Modèle modifié TEST')
  const after = await read(page)
  expect(after.logs[date].training).toEqual(original)
  const future = Object.entries(after.plannedSessions).find(([d, p]: [string, any]) => d > date && p.templateId === 'shoulders-arms') as [string, any]
  expect(future[1].template.name).toBe('Modèle modifié TEST')
})

test('mobile : bouton terminer et champs utilisables avec une fenêtre courte', async ({ page, isMobile }) => {
  test.skip(!isMobile, 'Contrôle tactile')
  await page.setViewportSize({ width: 360, height: 640 })
  await start(page)
  const finish = page.getByRole('button', { name: 'Terminer la séance', exact: true })
  await expect(finish).toBeInViewport()
  const first = page.locator('.journal-exercise.mobile-active')
  const charge = first.locator('input[type=number]').first()
  await charge.scrollIntoViewIfNeeded()
  await charge.fill('32.5')
  await expect(charge).toHaveValue('32.5')
  const del = first.locator('.delete-set').first()
  const box = await del.boundingBox()
  expect(box?.width).toBeGreaterThanOrEqual(44)
  expect(box?.height).toBeGreaterThanOrEqual(44)
  await expect(finish).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
})
