import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Clock3, Dumbbell, ListChecks, Pause, Play, Plus, Shuffle, TimerReset, Trash2 } from 'lucide-react'
import { useApp } from '../state/AppContext'
import { useJournalDate } from '../hooks/useJournalDate'
import { formatLongDate, isoDate } from '../domain/dates'
import { blankSet, changeSession, conventionLabels, elapsed, exerciseHistory, replaceExercise, startSession, targetText, templateForDate, validSet, volume, workSets } from '../domain/training'
import type { ExerciseDefinition, ExerciseLog, SetLog, TrainingSession } from '../domain/types'
import { formatNumber } from '../domain/format'
import { Button, Card, InfoBanner, PageHeader, ProgressBar } from '../components/ui'
import { ExplainedLabel } from '../components/HelpTooltip'
import { ExercisePicker, Modal, SessionsShell } from '../components/sessions/SessionsUI'

const duration = (ms: number) => `${Math.floor(ms / 60000).toString().padStart(2, '0')}:${Math.floor(ms / 1000 % 60).toString().padStart(2, '0')}`
export function SessionJournalPage() {
  const { state, transact, storageStatus } = useApp()
  const { selectedDate: date } = useJournalDate()
  const [params] = useSearchParams()
  const [now, setNow] = useState(Date.now())
  const [active, setActive] = useState(params.get('lineId') ?? '')
  const [correcting, setCorrecting] = useState(false)
  const [unlock, setUnlock] = useState(false)
  const [finish, setFinish] = useState(false)
  const [replacing, setReplacing] = useState<string | null>(null)
  const [global, setGlobal] = useState(false)
  const [globalChoice, setGlobalChoice] = useState<ExerciseDefinition | null>(null)
  const [deleting, setDeleting] = useState<{ line: string; set: SetLog; index: number } | null>(null)
  const [undo, setUndo] = useState<typeof deleting>(null)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const session = state.logs[date]?.training
  const template = templateForDate(state, date)
  const future = (params.get('date') ?? date) > isoDate()
  const readOnly = future || ((date < isoDate() || session?.status === 'completed') && !correcting)
  const lines = session?.exercises ?? []
  const currentLine = lines.find(e => e.id === active) ?? lines.find(e => !e.replacedById && e.sets.some(s => !s.completed)) ?? lines[0]
  const currentIndex = Math.max(0, lines.findIndex(e => e.id === currentLine?.id))
  const totalSets = lines.reduce((sum, e) => sum + e.sets.length, 0)
  const completedSets = lines.reduce((sum, e) => sum + e.sets.filter(s => s.completed).length, 0)
  const volumes = lines.filter(e => workSets(e).length).map(volume)
  const totalVolume = volumes.some(v => v === null) ? null : volumes.reduce<number>((sum, v) => sum + v!, 0)
  const restMs = Math.max(0, session?.restUntil ? session.restUntil - now : session?.restRemainingMs ?? 0)
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer) }, [])
  useEffect(() => { if (params.get('lineId')) document.getElementById(`exercise-${params.get('lineId')}`)?.scrollIntoView({ block: 'center' }) }, [params, session?.id])
  function update(update: (s: TrainingSession) => TrainingSession) { return transact(s => changeSession(s, date, update)) }
  function updateSet(line: ExerciseLog, set: SetLog, patch: Partial<SetLog>) {
    if (readOnly) return
    const next = { ...set, ...patch }
    if (next.completed && !validSet(next, line.convention)) { next.completed = false; setError('Série non validée : renseigne une charge et des répétitions valides (RIR de 0 à 10, facultatif).') }
    else setError('')
    update(s => ({ ...s, exercises: s.exercises.map(e => e.id === line.id ? { ...e, sets: e.sets.map(item => item.id === set.id ? next : item) } : e), ...(patch.completed && next.completed && s.autoRest && line.restSeconds ? { restUntil: Date.now() + line.restSeconds * 1000, restRemainingMs: undefined } : {}) }))
  }
  function removeSet(item: NonNullable<typeof deleting>) { if (update(s => ({ ...s, exercises: s.exercises.map(e => e.id === item.line ? { ...e, sets: e.sets.filter(set => set.id !== item.set.id) } : e) }))) { setUndo(item); setDeleting(null) } }
  function complete() { if (update(s => ({ ...s, status: 'completed', completedAt: Date.now(), elapsedMs: elapsed(s), runningSince: undefined, restUntil: undefined, restRemainingMs: undefined }))) { setFinish(false); setCorrecting(false); setMessage('Séance terminée et enregistrée. Les séries partielles sont conservées.') } }
  function applyReplacement(def: ExerciseDefinition, model: boolean) { if (replacing && transact(s => replaceExercise(s, date, replacing, def, model))) { setReplacing(null); setGlobalChoice(null); setGlobal(false); setMessage('Exercice remplacé. Les séries originales validées sont conservées.') } }
  if (future) return <SessionsShell><h1>Journal futur en lecture seule</h1><InfoBanner>Tu peux planifier cette journée, mais pas encore enregistrer de performances réelles.</InfoBanner><Link to={`/seances/planning?week=${params.get('date')}`}>Ouvrir son planning</Link></SessionsShell>
  return <SessionsShell><Link className="back-link" to={`/seances?date=${date}`}>‹ Mes séances</Link><PageHeader title={session?.name ?? template?.name ?? 'Jour de repos'} description={`${formatLongDate(date)} · ${session?.status === 'completed' ? 'Séance terminée' : session ? 'Séance en cours' : 'Séance prévue'}`} action={session ? <>{!readOnly && session.status !== 'completed' && <Button variant="secondary" onClick={() => update(s => s.runningSince ? { ...s, elapsedMs: elapsed(s), runningSince: undefined } : { ...s, runningSince: Date.now() })}>{session.runningSince ? <Pause /> : <Play />}{session.runningSince ? 'Pause' : 'Reprendre'}</Button>}<Button className="journal-finish-header" disabled={session.status === 'completed' || readOnly} onClick={() => completedSets < totalSets ? setFinish(true) : complete()}><CheckCircle2 />{session.status === 'completed' ? 'Séance terminée' : 'Terminer la séance'}</Button></> : undefined} />
    {message && <InfoBanner tone="success">{message}</InfoBanner>}{error && <p className="field-error" role="alert">{error}</p>}
    {readOnly && <InfoBanner>Lecture seule : historique protégé. <Button variant="secondary" onClick={() => setUnlock(true)}>Corriger cette séance</Button></InfoBanner>}
    <InfoBanner>Épaule gauche : aucune poussée jusqu’à validation médicale · amplitude indolore. Les suggestions du catalogue ne constituent pas une validation médicale.</InfoBanner>
    {!session && <Card className="session-panel"><h2>{template ? 'Prêt pour ta séance ?' : 'Aucune séance prévue'}</h2>{template ? <><p>{template.exercises.length} exercices · {template.exercises.reduce((sum, e) => sum + (e.setCount ?? 0), 0)} séries prévues. Les champs réels seront vides au démarrage.</p><ol>{template.exercises.map(e => <li key={e.id}>{e.name} — {targetText(e)}</li>)}</ol><Button disabled={readOnly || !template.exercises.length} onClick={() => { if (transact(s => startSession(s, date, template.id))) setMessage('Séance démarrée. Tu peux saisir tes séries.') }}><Play /> Démarrer la séance</Button></> : <p>Choisis un modèle dans le planning pour t’entraîner ce jour-là.</p>}<Link className="button button-secondary" to={`/seances/planning?week=${date}&date=${date}`}>Modifier le planning</Link></Card>}
    {session && <><div className="journal-kpis"><Card><Clock3 /><div><span>Durée active</span><strong>{session.startedAt ? duration(elapsed(session, now)) : '—'}</strong></div></Card><Card><ListChecks /><div><ExplainedLabel help="Nombre de séries validées sur le nombre de séries de cette occurrence. Ce n’est pas une mesure de progrès sportif.">Séries validées</ExplainedLabel><strong>{completedSets} / {totalSets}</strong></div></Card><Card><Dumbbell /><div><ExplainedLabel help="Somme des charges × répétitions des séries de travail validées, sans doublage arbitraire. Indisponible si une convention de charge est inconnue, assistée ou au poids du corps.">Volume validé</ExplainedLabel><strong>{totalVolume === null ? '—' : formatNumber(totalVolume)} <small>kg</small></strong></div></Card></div>
    <div className="journal-mobile-progress"><span>Exercice {currentIndex + 1} sur {lines.length}</span><ProgressBar value={completedSets} max={totalSets} /></div>
    <div className="journal-exercises">{lines.map((line, index) => {
      const prior = exerciseHistory(state, line.exerciseId ?? '', line.equipmentId ?? '', '0000-01-01', date).filter(h => h.date < date).at(-1)
      return <Card key={line.id} id={`exercise-${line.id}`} className={`journal-exercise ${currentLine?.id === line.id ? 'mobile-active' : ''} ${params.get('lineId') === line.id ? 'highlight-exercise' : ''}`}><div className="journal-exercise-heading"><span className="exercise-index">{index + 1}</span><div><h2>{line.name}</h2><p>{targetText(line)}{line.targetRir !== undefined ? ` · RIR ${line.targetRir}` : ''}</p><small>{line.equipmentId === 'legacy-unspecified' ? 'Matériel historique non précisé' : line.equipmentId} · {conventionLabels[line.convention ?? 'unknown']}</small><p className="last-performance">{prior ? `Dernière fois : ${prior.best.loadKg ?? 'PDC'} kg × ${prior.best.reps}` : 'Première séance enregistrée'}</p>{line.replacesId && <span className="day-pill">Remplacement ponctuel</span>}{line.replacedById && <span className="day-pill">Original conservé — remplacé</span>}</div><div className="exercise-controls"><button className="icon-button" aria-label={`Afficher les séries de ${line.name}`} aria-expanded={currentLine?.id === line.id} onClick={() => setActive(line.id)}><ChevronDown /></button>{!readOnly && !line.replacedById && <><Button variant="secondary" onClick={() => update(s => ({ ...s, exercises: s.exercises.map(e => e.id === line.id ? { ...e, sets: [...e.sets, blankSet()] } : e) }))}><Plus /> Ajouter une série</Button><Button variant="ghost" aria-label={`Remplacer ${line.name}`} onClick={() => { setReplacing(line.id); setGlobal(false) }}><Shuffle /></Button></>}</div></div>
      {line.note && <p className="session-hint">{line.note}</p>}
      <div className="set-table" role="group" aria-label={`Séries de ${line.name}`}><div className="set-table-heading"><span>Série</span><span>Charge (kg)</span><span>Reps</span><ExplainedLabel help="Répétitions en réserve, facultatif. 0 signifie aucune répétition supplémentaire possible.">RIR</ExplainedLabel><span>Valider</span><span /></div>{line.sets.map((set, setIndex) => <div className={`set-row ${set.completed ? 'validated' : ''}`} key={set.id}><span><span>{setIndex + 1}</span><select aria-label={`Type série ${setIndex + 1} ${line.name}`} disabled={readOnly} value={set.kind ?? 'work'} onChange={e => updateSet(line, set, { kind: e.target.value as SetLog['kind'] })}><option value="work">Travail</option><option value="warmup">Échauff.</option></select></span><input aria-label={`Charge série ${setIndex + 1} ${line.name}`} inputMode="decimal" type="number" min={0} max={2000} step="any" placeholder="kg" disabled={readOnly} value={set.loadKg ?? ''} onChange={e => updateSet(line, set, { loadKg: e.target.value === '' ? undefined : +e.target.value })} /><input aria-label={`Répétitions série ${setIndex + 1} ${line.name}`} inputMode="numeric" type="number" min={1} max={1000} placeholder="reps" disabled={readOnly} value={set.reps ?? ''} onChange={e => updateSet(line, set, { reps: e.target.value === '' ? undefined : +e.target.value })} /><input aria-label={`RIR série ${setIndex + 1} ${line.name}`} inputMode="numeric" type="number" min={0} max={10} placeholder="—" disabled={readOnly} value={set.rir ?? ''} onChange={e => updateSet(line, set, { rir: e.target.value === '' ? undefined : +e.target.value })} /><button className={`validate-set ${set.completed ? 'checked' : ''}`} aria-label={`${set.completed ? 'Dévalider' : 'Valider'} série ${setIndex + 1} ${line.name}`} aria-pressed={set.completed} disabled={readOnly} onClick={() => updateSet(line, set, { completed: !set.completed })}><Check /></button><button className="delete-set" aria-label={`Retirer série ${setIndex + 1} ${line.name}`} disabled={readOnly} onClick={() => { const item = { line: line.id, set, index: setIndex }; if (set.completed) setDeleting(item); else removeSet(item) }}><Trash2 /></button></div>)}</div>
      {!line.sets.length && <p>Aucune série enregistrée pour cet exercice original.</p>}
      {!readOnly && !line.replacedById && <div className="mobile-exercise-actions"><Button variant="secondary" onClick={() => { setReplacing(line.id); setGlobal(false) }}><Shuffle /> Remplacer l’exercice</Button><Button variant="secondary" onClick={() => update(s => ({ ...s, exercises: s.exercises.map(e => e.id === line.id ? { ...e, sets: [...e.sets, blankSet()] } : e) }))}><Plus /> Ajouter une série</Button></div>}
    </Card>})}</div>
    {undo && <InfoBanner>Série retirée. <Button variant="secondary" onClick={() => { if (update(s => ({ ...s, exercises: s.exercises.map(e => { if (e.id !== undo.line || e.sets.some(set => set.id === undo.set.id)) return e; const sets = [...e.sets]; sets.splice(undo.index, 0, undo.set); return { ...e, sets } }) }))) setUndo(null) }}>Annuler la suppression</Button></InfoBanner>}
    <div className="journal-mobile-nav"><Button variant="secondary" disabled={currentIndex === 0} onClick={() => setActive(lines[currentIndex - 1]?.id)}><ChevronLeft /> Précédent</Button><Button variant="secondary" disabled={currentIndex === lines.length - 1} onClick={() => setActive(lines[currentIndex + 1]?.id)}>Exercice suivant <ChevronRight /></Button></div>
    {!readOnly && session.status !== 'completed' && <Card className="session-rest"><TimerReset /><div><span>Repos</span><strong>{duration(restMs)}</strong></div><Button variant="secondary" onClick={() => update(s => ({ ...s, restUntil: Date.now() + (currentLine?.restSeconds ?? 90) * 1000, restRemainingMs: undefined }))}>Démarrer le repos</Button><Button variant="ghost" onClick={() => update(s => s.restUntil ? { ...s, restUntil: Math.max(Date.now(), s.restUntil) + 30000 } : { ...s, restRemainingMs: (s.restRemainingMs ?? 0) + 30000 })}>+30 s</Button><Button variant="ghost" aria-label={session.restUntil ? 'Mettre le repos en pause' : 'Reprendre le repos'} onClick={() => update(s => s.restUntil ? { ...s, restRemainingMs: Math.max(0, s.restUntil - Date.now()), restUntil: undefined } : { ...s, restUntil: Date.now() + (s.restRemainingMs ?? 90000), restRemainingMs: undefined })}>{session.restUntil ? <Pause /> : <Play />}</Button><label className="check-label"><input type="checkbox" checked={session.autoRest ?? true} onChange={e => update(s => ({ ...s, autoRest: e.target.checked }))} /> Repos automatique après validation</label></Card>}
    {correcting && session.status === 'completed' && <Button onClick={() => { setCorrecting(false); setMessage('Correction conservée dans la séance d’origine.') }}>Terminer la correction</Button>}
    <p className="session-hint">{storageStatus} · Données uniquement sur cet appareil.</p><div className="journal-finish-mobile"><Button disabled={session.status === 'completed' || readOnly} onClick={() => completedSets < totalSets ? setFinish(true) : complete()}><CheckCircle2 />{session.status === 'completed' ? 'Séance terminée' : 'Terminer la séance'}</Button></div>
    </>}
    {unlock && <Modal title="Corriger l’historique de cette séance ?" onClose={() => setUnlock(false)}><p>Tu modifieras les performances de cette occurrence uniquement. Le modèle et les autres journées restent inchangés. Il ne s’agit pas de recommencer ni d’effacer la séance.</p><Button onClick={() => { setCorrecting(true); setUnlock(false) }}>Autoriser la correction de la séance</Button><Button variant="secondary" onClick={() => setUnlock(false)}>Annuler</Button></Modal>}
    {finish && <Modal title="Terminer une séance partielle ?" onClose={() => setFinish(false)}><p>{completedSets} séries validées sur {totalSets}. Les séries non validées resteront des brouillons et ne compteront pas dans les statistiques.</p><Button onClick={complete}>Terminer en l’état</Button><Button variant="secondary" onClick={() => setFinish(false)}>Continuer la séance</Button></Modal>}
    {replacing && !globalChoice && <ExercisePicker draftKey={`journal-${date}-${replacing}`} title="Remplacer un exercice" onClose={() => setReplacing(null)} onPick={def => global ? setGlobalChoice(def) : applyReplacement(def, false)}><div className="session-replacement-scope"><h3>Appliquer le changement</h3><label className="scope-option"><input type="radio" name="replacement-scope" checked={!global} onChange={() => setGlobal(false)} /><span>Cette séance uniquement<small>Le modèle reste inchangé.</small></span></label><label className="scope-option"><input type="radio" name="replacement-scope" checked={global} onChange={() => setGlobal(true)} /><span>Mettre aussi à jour le modèle<small>Pour les nouvelles planifications uniquement, après confirmation.</small></span></label><InfoBanner>Les séries déjà enregistrées sur l’original seront conservées.</InfoBanner></div></ExercisePicker>}
    {globalChoice && <Modal title="Modifier aussi le modèle global ?" onClose={() => setGlobalChoice(null)}><p>{globalChoice.name} remplacera l’exercice dans cette occurrence et dans les nouvelles planifications du modèle. Les occurrences déjà planifiées ou réalisées ne changent pas.</p><Button onClick={() => applyReplacement(globalChoice, true)}>Confirmer le remplacement global</Button><Button variant="secondary" onClick={() => setGlobalChoice(null)}>Retour</Button></Modal>}
    {deleting && <Modal title="Retirer cette série validée ?" onClose={() => setDeleting(null)}><p>{deleting.set.loadKg ?? '—'} kg × {deleting.set.reps} répétitions. Tu pourras annuler la suppression tant que ce journal reste ouvert.</p><Button variant="danger" onClick={() => removeSet(deleting)}>Confirmer la suppression</Button><Button variant="secondary" onClick={() => setDeleting(null)}>Annuler</Button></Modal>}
  </SessionsShell>
}
